@Tutorial9_HostAddress = http://localhost:5027

### Add Product to the Warehouse[Valid Data] -> 201 Created
POST {{Tutorial9_HostAddress}}/api/warehouse
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 1,
  "Amount": 20,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}

### Add Product to the Warehouse[Invalid Data][IdProduct does not exist] -> 500 Internal Server Error
POST {{Tutorial9_HostAddress}}/api/warehouse
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 4,
  "IdWarehouse": 1,
  "Amount": 20,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}

### Add Product to the Warehouse[Invalid Data][IdWarehouse does not exist] -> 500 Internal Server Error
POST {{Tutorial9_HostAddress}}/api/warehouse
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 5,
  "Amount": 20,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}

### Add Product to the Warehouse[Invalid Data][Amount is too big] -> 500 Internal Server Error
POST {{Tutorial9_HostAddress}}/api/warehouse
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 1,
  "Amount": 126,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}




### Add Product to the Warehouse using Procedure -> 201 Created
POST {{Tutorial9_HostAddress}}/api/warehouse/proc
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 1,
  "Amount": 20,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}

### Add Product to the Warehouse using Procedure[Invalid Data][IdProduct does not exist] -> 500 Internal Server Error
POST {{Tutorial9_HostAddress}}/api/warehouse/proc
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 4,
  "IdWarehouse": 1,
  "Amount": 20,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}

### Add Product to the Warehouse using Procedure[Invalid Data][IdWarehouse does not exist] -> 500 Internal Server Error
POST {{Tutorial9_HostAddress}}/api/warehouse
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 5,
  "Amount": 20,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}

### Add Product to the Warehouse using Procedure[Invalid Data][Amount is too big] -> 500 Internal Server Error
POST {{Tutorial9_HostAddress}}/api/warehouse
Accept: application/json
Content-Type: application/json

{
  "IdProduct": 1,
  "IdWarehouse": 1,
  "Amount": 126,
  "CreatedAt": "2025-05-11T19:30:00.511Z"
}